name: build & run docker container for testing api in this container

on:
    push: 
        branches: ["docker", "main", "api"]
    pull_request:
        branches: ["docker"]

    workflow_dispatch:
        inputs:
            logLevel:
                description: 'Log level'
                required: true
                default: 'warning'
                type: choice
                options:
                - info
                - debug
            running_description:
                description: 'description'
                required: false
                default: "~"
                type: string

jobs:
    testing:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            
            - name: Install docker
              uses: docker/setup-buildx-action@v3

            - name: Updating system
              run: apt-get update && apt-get upgrade

            - name: Installing docker io & compose
              run: apt-get install docker.io docker-compose

            - name: Docker compose up
              run: docker-compose up
