name: build & run docker container for testing api in this container

on:
    push: 
        branches: ["docker", "api"]
    pull_request:
        branches: ["docker"]

    workflow_dispatch:
        inputs:
            logLevel:
                description: 'Log level'
                required: true
                default: 'warning'
                type: choice
                options:
                - info
                - debug
            running_description:
                description: 'description'
                required: false
                default: "~"
                type: string

jobs:
    testing:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            
            - uses: hoverkraft-tech/compose-action@v2.0.0
